### PR TITLE
Add Carthage Support and Fix Compilation Error

### PR DESCRIPTION
**Pull request by evandcoleman**
We're looking to implement this library in one of our apps at TKWW. Just had to make a few changes to support our use case and figured the public would benefit from these as well.

- Added the Xcode project to git to enable Carthage support
- Made the function builders public so that they can be used outside the library

### CODE REVIEW

**Comment by NicholasBellucci** [comment]
Looks good to me. Could you update the installation section of the README to include how it should be added with Carthage? I have not previously used Carthage.

**Comment by evandcoleman** [comment]
@NicholasBellucci Sure! Done!

**Comment by evandcoleman** [comment]
Thanks for the quick turnaround! We're super excited to start using this!

**Comment by NicholasBellucci** [comment]
Please feel free to open any issues or contribute more if any issues are found! I plan to keep this project as up to date as I can.

**Pull request merged**
